include: "rules/common.smk"
include: "rules/fastp.smk"


if config.get("load_fair_genome_indexer", True):

    include: "rules/fair_genome_indexer_pipeline.smk"


include: "rules/bowtie2_sambamba_meta.smk"
include: "rules/picard_metrics.smk"
include: "rules/multiqc.smk"


use rule target from fair_genome_indexer with:
    input:
        unpack(get_targets),
