name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches-ignore: []

jobs:
  formatting:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: read
      # To report GitHub Actions status checks
      statuses: read
      
    steps:
    - name: Checkout with submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0
      
    - name: Formatting
      uses: super-linter/super-linter@v7.3.0            
      env:
        DEFAULT_BRANCH: main
        VALIDATE_ALL_CODEBASE: false
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VALIDATE_SNAKEMAKE_SNAKEFMT: true

  linting-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Linting
      uses: snakemake/snakemake-github-action@v1.25.1
      with:
        directory: .test
        snakefile: workflow/Snakefile
        args: "--lint"

  
  linting-workflow:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Linting
      uses: snakemake/snakemake-github-action@v1.25.1
      with:
        directory: .
        snakefile: workflow/Snakefile
        args: "--lint"

  run-workflow:
    runs-on: ubuntu-latest
    needs:
      - linting-workflow
      - linting-tests
      - formatting
    steps:
    - name: Checkout repository with submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Test workflow
      uses: snakemake/snakemake-github-action@v1.25.1
      with:
        directory: .test
        snakefile: workflow/Snakefile
        args: "--software-deployment-method conda --show-failed-logs --cores 2 --conda-cleanup-pkgs cache"
    - name: Test report
      uses: snakemake/snakemake-github-action@v1.25.1
      with:
        directory: .test
        snakefile: workflow/Snakefile
        args: "--software-deployment-method conda --cores 2 --report report.zip"
